import localFont from "next/font/local";
import "./globals.css";
import { ShoppingCart, Search, Menu } from 'lucide-react';

import Link from "next/link";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <nav className="  bg-gradient-to-r from-blue-500 to-purple-600">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center">
              <span className="text-white text-xl font-bold">E-commerce</span>
            </div>
            <div className="hidden md:block">
              <div className="ml-10 flex items-baseline space-x-4">
                <Link className="text-white hover:bg-white hover:bg-opacity-20 px-3 py-2 rounded-md" href="/">Home</Link>
                <Link className="text-white hover:bg-white hover:bg-opacity-20 px-3 py-2 rounded-md" href="/about">About</Link>
                <Link className="text-white hover:bg-white hover:bg-opacity-20 px-3 py-2 rounded-md" href="/AllProducts">All Products</Link>
                <Link className="text-white hover:bg-white hover:bg-opacity-20 px-3 py-2 rounded-md" href="/AllPosts">All Posts</Link>

              </div>
            </div>
            <div className="flex items-center">
              <button className="text-white p-2 rounded-full hover:bg-white hover:bg-opacity-20">
                <Search className="h-6 w-6" />
              </button>
              <button className="text-white p-2 rounded-full hover:bg-white hover:bg-opacity-20 ml-4">
               <Link href={'/cart'} > <ShoppingCart className="h-6 w-6" /></Link>
              </button>
              <button className="text-white p-2 rounded-full hover:bg-white hover:bg-opacity-20 ml-4 md:hidden">
                <Menu className="h-6 w-6" />
              </button>
            </div>
          </div>
        </div>
      </nav>
        {children}
      </body>
    </html>
  );
}
